### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by tebriz159** [superquizsite/superquizsite.github.io#3]
Hello, I'm a logo designer and I can make a free logo for your project. Do you want it?
Logo fixed

**Comment by RDIL** [comment]
Sure thanks!  
P.S. quick question: how did you find our project?

**Comment by tebriz159** [comment]
I was looking for new updated projects which has website and I found your project there. I'll start to design a logo for this project.

**Comment by tebriz159** [comment]
Logo is ready to use. Do you like it? 
All files is here: https://drive.google.com/open?id=1FgX97QtUUDD10j5pKU7o9nOTa-zjebR2

![superquiz](https://user-images.githubusercontent.com/31902754/50708876-b0a04b80-101a-11e9-8944-f9bc8ecc9b60.png)

**Comment by RDIL** [comment]
Love it!!  Thanks 👍

**Comment by tebriz159** [comment]
You're faster than my internet :D You're welcome. I'm glad that you like it )

**Comment by RDIL** [comment]
Implementing this now.

**Comment by tebriz159** [comment]
Pls let me know when you done, I want to see how it looks on the website.

**Comment by RDIL** [comment]
@tebriz159 I put it as the @superquizsite organization logo, not quite sure yet where on the website I should put it, will let you know when I do implement it though.

**Comment by RDIL** [comment]
I edited your comment so I can remember to do this.

**Comment by tebriz159** [comment]
Thanks man, if you need me to design a logo for any project I'll help you.

**Comment by RDIL** [comment]
@tebriz159 can you make the background of the image you linked above transparent?  I can put it on the site once that happens.  Thanks!

**Comment by RDIL** [comment]
@tebriz159?

**Comment by tebriz159** [comment]
@RDIL Sorry mate, I'm sick these days, that's why I couldn't answer. What kind a background do you want? Can you give me information about shape and color?

**Comment by RDIL** [comment]
@tebriz159 No worries, can you just make the background of the one above transparent?

**Comment by tebriz159** [comment]
Like this? https://drive.google.com/open?id=1t4ww3DoBkZ83GKZi57Y_XXYrqSqaO6Rp

**Comment by RDIL** [comment]
That's good, thanks!  I'll put it on the site when I get home.

**Comment by RDIL** [comment]
Adding now.

**Comment by RDIL** [comment]
Huh, it’s rendering inside the div which isn’t right.

**Comment by RDIL** [comment]
@tebriz159 I think I fixed it in f1e94c6 , try now?

**Comment by tebriz159** [comment]
@RDIL I tryed but ![2019-01-21_015319](https://user-images.githubusercontent.com/31902754/51466597-69ef6880-1d1f-11e9-8951-0b27f24841f3.png)

**Comment by RDIL** [comment]
Huh, I’ll try fixing it again now.

**Comment by RDIL** [comment]
@tebriz159 fixed.  I forgot that images take `src` as a param for the location instead of `href`.  Sorry about that.  It should be on the website now, I queued a rebuild which should be done in a few minutes.   Tell me if there is anything I can do for you, I really appreciate your design skills!

**Comment by RDIL** [comment]
@tebriz159 does it look good now?

**Comment by tebriz159** [comment]
I 've posted this contribution on steemit last week. You can take a look if you want https://steemit.com/utopian-io/@tebriz/logo-design-for-superquiz
It was nice to work with you, please let me know when you need a logo design )

**Comment by RDIL** [comment]
Thanks so much!!! :D
